/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EvidenceRegistry {
  export type EvidenceStruct = {
    caseId: string;
    version: BigNumberish;
    reportHash: BytesLike;
    timestamp: BigNumberish;
    submittedBy: AddressLike;
  };

  export type EvidenceStructOutput = [
    caseId: string,
    version: bigint,
    reportHash: string,
    timestamp: bigint,
    submittedBy: string
  ] & {
    caseId: string;
    version: bigint;
    reportHash: string;
    timestamp: bigint;
    submittedBy: string;
  };
}

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedInvestigators"
      | "getEvidence"
      | "getEvidenceCount"
      | "getLatestEvidence"
      | "owner"
      | "setInvestigator"
      | "storeEvidence"
      | "transferOwnership"
      | "verifyReportHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EvidenceStored"
      | "InvestigatorUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedInvestigators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidence",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestEvidence",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setInvestigator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "storeEvidence",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyReportHash",
    values: [string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedInvestigators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInvestigator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyReportHash",
    data: BytesLike
  ): Result;
}

export namespace EvidenceStoredEvent {
  export type InputTuple = [
    caseId: string,
    version: BigNumberish,
    reportHash: BytesLike,
    timestamp: BigNumberish,
    submittedBy: AddressLike
  ];
  export type OutputTuple = [
    caseId: string,
    version: bigint,
    reportHash: string,
    timestamp: bigint,
    submittedBy: string
  ];
  export interface OutputObject {
    caseId: string;
    version: bigint;
    reportHash: string;
    timestamp: bigint;
    submittedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestigatorUpdatedEvent {
  export type InputTuple = [investigator: AddressLike, allowed: boolean];
  export type OutputTuple = [investigator: string, allowed: boolean];
  export interface OutputObject {
    investigator: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedInvestigators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getEvidence: TypedContractMethod<
    [caseId: string, index: BigNumberish],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;

  getEvidenceCount: TypedContractMethod<[caseId: string], [bigint], "view">;

  getLatestEvidence: TypedContractMethod<
    [caseId: string],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setInvestigator: TypedContractMethod<
    [investigator: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  storeEvidence: TypedContractMethod<
    [caseId: string, reportHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyReportHash: TypedContractMethod<
    [caseId: string, version: BigNumberish, reportHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedInvestigators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [caseId: string, index: BigNumberish],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceCount"
  ): TypedContractMethod<[caseId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestEvidence"
  ): TypedContractMethod<
    [caseId: string],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setInvestigator"
  ): TypedContractMethod<
    [investigator: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeEvidence"
  ): TypedContractMethod<
    [caseId: string, reportHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyReportHash"
  ): TypedContractMethod<
    [caseId: string, version: BigNumberish, reportHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "EvidenceStored"
  ): TypedContractEvent<
    EvidenceStoredEvent.InputTuple,
    EvidenceStoredEvent.OutputTuple,
    EvidenceStoredEvent.OutputObject
  >;
  getEvent(
    key: "InvestigatorUpdated"
  ): TypedContractEvent<
    InvestigatorUpdatedEvent.InputTuple,
    InvestigatorUpdatedEvent.OutputTuple,
    InvestigatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "EvidenceStored(string,uint256,bytes32,uint256,address)": TypedContractEvent<
      EvidenceStoredEvent.InputTuple,
      EvidenceStoredEvent.OutputTuple,
      EvidenceStoredEvent.OutputObject
    >;
    EvidenceStored: TypedContractEvent<
      EvidenceStoredEvent.InputTuple,
      EvidenceStoredEvent.OutputTuple,
      EvidenceStoredEvent.OutputObject
    >;

    "InvestigatorUpdated(address,bool)": TypedContractEvent<
      InvestigatorUpdatedEvent.InputTuple,
      InvestigatorUpdatedEvent.OutputTuple,
      InvestigatorUpdatedEvent.OutputObject
    >;
    InvestigatorUpdated: TypedContractEvent<
      InvestigatorUpdatedEvent.InputTuple,
      InvestigatorUpdatedEvent.OutputTuple,
      InvestigatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
