/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EvidenceRegistry } from "./EvidenceRegistry";
export * as factories from "./factories";
export { EvidenceRegistry__factory } from "./factories/EvidenceRegistry__factory";
