/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EvidenceRegistry } from './EvidenceRegistry.js';
export * as factories from './factories/index.js';
export { EvidenceRegistry__factory } from './factories/EvidenceRegistry__factory.js';